/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const __wbg_trafficlight_free: (a: number, b: number) => void;
export const trafficlight_red: () => number;
export const trafficlight_yellow: () => number;
export const trafficlight_green: () => number;
export const trafficlight_to_string: (a: number) => [number, number];
export const __wbg_message_free: (a: number, b: number) => void;
export const message_quit: () => number;
export const message_move_to: (a: number, b: number) => number;
export const message_write: (a: number, b: number) => number;
export const message_change_color: (a: number, b: number, c: number) => number;
export const message_process: (a: number) => [number, number];
export const divide: (a: number, b: number) => [number, number];
export const __wbg_either_free: (a: number, b: number) => void;
export const either_left: (a: number) => number;
export const either_right: (a: number, b: number) => number;
export const either_format: (a: number) => [number, number];
export const __wbg_point_free: (a: number, b: number) => void;
export const point_new: (a: number, b: number) => number;
export const point_format: (a: number) => [number, number];
export const __wbg_color_free: (a: number, b: number) => void;
export const color_red: () => number;
export const color_green: () => number;
export const color_blue: () => number;
export const color_rgb: (a: number, b: number, c: number) => number;
export const color_to_rgb: (a: number) => [number, number];
export const color_brightness: (a: number) => number;
export const __wbg_direction_free: (a: number, b: number) => void;
export const direction_north: () => number;
export const direction_south: () => number;
export const direction_east: () => number;
export const direction_west: () => number;
export const direction_describe: (a: number) => [number, number];
export const first_element: (a: number, b: number) => [number, number];
export const run_code: (a: number, b: number) => [number, number];
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __wbindgen_start: () => void;
